In [2]:
import numpy as np

# Simulado para a prova

## Exercício 1

Dadas as matrizes:

$$
A = \begin{bmatrix} 0 & 1\\ 2 & 3 \end{bmatrix} \\

B = \begin{bmatrix} 7 & 9\\ 23 & -1 \end{bmatrix}
$$

calcule:

1. $AB$
1. $BA$
1. $A \odot B$
1. $A^TB$
1. $AB^{-1}$

$(AB)^T = B^T A^T$


In [3]:
a = np.array([[0, 1],
              [2, 3]])

b = np.array([[7, 9],
              [23, -1]])

eq1 = a @ b
eq2 = b @ a
eq3 = a * b
eq4 = a.T @ b
eq5 = a @ np.linalg.inv(b)

part1 = eq1.T 
part2 = b.T @ a.T

print(eq1)
print(eq2)
print(eq3)
print(eq4)
print(eq5)
print(part1)
print(part2)

[[23 -1]
 [83 15]]
[[18 34]
 [-2 20]]
[[ 0  9]
 [46 -3]]
[[46 -2]
 [76  6]]
[[ 0.10747664 -0.03271028]
 [ 0.3317757  -0.01401869]]
[[23 83]
 [-1 15]]
[[23 83]
 [-1 15]]


# Exercício 2

Eu tenho uma núvem de pontos que está em um quadrado cujo centro é o ponto $(-2,3)$. Qual é a matriz que transforma essa núvem de pontos em uma núvem semelhante, rotacionada de 30 graus no sentido anti-horário, centrada em $(5,5)$? Se precisar, use coordenadas homogêneas!

$$
R = 
\begin{bmatrix}
    \cos(\theta) & -\sin(\theta) & 0 \\
    \sin(\theta) & \cos(\theta) & 0 \\
    0 & 0 & 1
\end{bmatrix}
$$

$$
T = 
\begin{bmatrix}
    1 & 0 & \Delta x \\
    0 & 1 & \Delta y \\
    0 & 0 & 1
\end{bmatrix}
$$

# Exercício 3

Quatro amigos foram a uma lanchonete, e fizeram os seguintes pedidos:

* 1 x-salada e 1 suco de laranja, no total de R$10,00,
* 2 x-salada e 2 suco de laranja, no total de R$20,00,
* 2 x-salada e 1 suco de laranja, no total de R$13,00,
* 4 x-salada e 2 suco de laranja, no total de R$26,00.


1. Qual é o preço do x-salada?
1. Qual é o preço do suco de laranja?
1. Qual é o valor de uma compra de 1 x-salada e 2 sucos de laranja?


In [5]:
#Parte 1 - Qual é o preço do x-salada e do suco de laranja?

pedidos = np.array([[1, 1],
                    [2, 1]])

total = np.array([[10],
                   [13]])

precos = np.linalg.solve(pedidos, total)
print(precos)


#Parte 2 - Qual é o valor de uma compra de 1 x-salada e 2 sucos de laranja?

compra = np.array([[1, 2]])
preco = compra @ precos
print(preco)

[[3.]
 [7.]]
[[17.]]


# Exercício 4

Cada real investido na empresa E1 deu um retorno de 50 centavos ao fim de um ano. Cada real investido na empresa E2 deu um retorno de 10 centavos ao fim de um ano. Uma corretora propôs duas carteiras: C1, em que cada real é dividido igualmente entre as empresas E1 e E2, e C2, que tem 75% de aplicação na empresa E1 e 25% na empresa E2.

1. Se um investidor tem 5000 reais investidos na carteira C1 e 1000 na carteira C2, qual é o seu investimento nas empresas E1 e E2?
1. Se um investidor tem 2000 reais investidos diretamente na empresa E1, e 2000 reais na empresa E2, qual seria o investimento nas carteiras C1 e C2 equivalente?
1. Qual é a matriz que permite transformar investimentos nas empresas E1 e E2 em investimentos nas carteiras C1 e C2?

$$
E_1 = 0.5 C_1 + 0.75 C_2 \\
E_2 = 0.5 C_1 + 0.25 C_2 
$$

$$
E = \begin{bmatrix} 0.5 & 0.75 \\ 0.5 & 0.25 \end{bmatrix} C
$$

In [7]:
#Parte 1 - Se um investidor tem 5000 reais investidos na carteira C1 e 1000 na carteira C2, qual é o seu investimento nas empresas E1 e E2?

retorno = np.array([[0.5, 0.75],
                    [0.5, 0.25]])

carteira = np.array([[5000],
                    [1000]])

investimentos = retorno @ carteira
print(investimentos)


#Parte 2 - Se um investidor tem 2000 reais investidos diretamente na empresa E1, e 2000 reais na empresa E2, qual seria o investimento nas carteiras C1 e C2 equivalente?

investimento = np.array([[2000], 
                         [2000]])

carteira = np.linalg.inv(retorno) @  investimento
print(carteira)

[[3250.]
 [2750.]]
[[4000.]
 [   0.]]


# Exercício 5

Escreva o vetor $x$ tal que:

$$
\begin{bmatrix} -5 \\ 3 \end{bmatrix} = \begin{bmatrix} 0 & 1\\ 2 & 3 \end{bmatrix} x
$$

In [6]:
a = np.array([[-5],
              [3]])

b = np.array([[0, 1],
              [2, 3]])

x = np.linalg.inv(b) @ a
print(x)

[[ 9.]
 [-5.]]


# Exercício 6


Olhando uma foto do mapa em satélite da região próxima à Vila Olímpia, vemos a seguinte situação:

* O Insper, que está na latitude/longitude `[-23.59857192474643, -46.67653800340679]`, está no pixel `(400, 100)`.
* A escola Móbile, originalmente em `[-23.598451299397993, -46.66985259860919]`, está no pixel `(400, 200)`.
* O cachorródromo do parque Ibirapuera, que fica em `[-23.59247353738838, -46.66154847926121]`, está no pixel `(200, 400)`

Em que pixel deve aparecer o Burguer King, que fica na esquina da Avenida Santo Amaro com a Hélio Pelegrino, na latitude/longitude `[-23.597723757411057, -46.67377935273308]`?